### ISSUE TITLE
Getting "Definition for rule 'import-alias/import-alias' was not found  import-alias/import-alias"

### ISSUE THREAD

**Issue by on3dd** [steelsojka/eslint-import-alias#4]
My .eslintrc.js:
```js
module.exports = {
  // ...
  rules: {
    // ...
    "import-alias/import-alias": [
      "error",
      {
        relativeDepth: 0,
        // rootDir: path.resolve(__dirname, ".."),
        aliases: [
          // Example: rewrites imports pointing to `src/modules/app/index.js` to `~/modules/app/index.js`
          { alias: "~", matcher: "^src" }
        ]
      }
    ]
  }
};
```

Any ideas how can I solve this problem?

**Comment by mattsmith-dns** [comment]
I hit this too. Docs may need a refresh.

```
plugins: [
  "import-alias"
],
rules: {
  "import-alias/import-alias": [ ... ]
}
```

**Comment by on3dd** [comment]
> I hit this too. Docs may need a refresh.
> 
> ```
> plugins: [
>   "import-alias"
> ],
> rules: {
>   "import-alias/import-alias": [ ... ]
> }
> ```

Thanks for your reply, I'll try it a little later

**Comment by on3dd** [comment]
> I hit this too. Docs may need a refresh.
> 
> ```
> plugins: [
>   "import-alias"
> ],
> rules: {
>   "import-alias/import-alias": [ ... ]
> }
> ```

Sorry for veeery late answer, but yeah, it's a solution, thanks! 👍🏻

**Comment by jordanmkoncz** [comment]
Adding "import-alias" to "plugins" fixed this issue for me too, looks like the README currently doesn't mention that this needs to be done.
